### ISSUE TITLE
Forum link

### ISSUE THREAD

**Issue by harry-bridge** [nottinghamtec/Main-Website#41] opened 2016-03-21 21:42 UTC
Where do we want this thing, in the footer and possibly somewhere else? Maybe?

**Comment by samozzy** [comment] 2016-03-25 01:40
I was thinking in the dropdown. While it's a bit in-your-face, it's sort of where members are going to look...

**Comment by samozzy** [comment] 2016-03-25 01:41
Duplicate of #39

**Comment by tomtom5152** [comment] 2016-03-27 19:43
Closed as duplicate of #39

**Closed as completed by tomtom5152** 2016-03-27 19:43 UTC
Labels: duplicate, enhancement
